using LeafletBE.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddOpenApi();

builder.Services.AddDbContext<AppDbContext>(opt =>
    opt.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddCors(opt =>
    opt.AddDefaultPolicy(p =>
        p.WithOrigins("http://localhost:5173").AllowAnyMethod().AllowAnyHeader()));

var app = builder.Build();

if (app.Environment.IsDevelopment())
    app.MapOpenApi();

app.UseCors();
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

// Initialize DB: enable TimescaleDB extension and create schema
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.ExecuteSqlRawAsync("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;");
    await db.Database.EnsureCreatedAsync();
    await db.Database.ExecuteSqlRawAsync(
        "SELECT create_hypertable('gps_tracks', 'time', if_not_exists => TRUE);");
    //// EnsureCreatedAsync skips if any table exists — create new tables manually (idempotent)
    //await db.Database.ExecuteSqlRawAsync("""
    //    CREATE TABLE IF NOT EXISTS vehicles (
    //        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    //        vehicle_id  TEXT NOT NULL,
    //        name        TEXT NOT NULL,
    //        type        TEXT,
    //        description TEXT,
    //        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    //        CONSTRAINT uq_vehicles_vehicle_id UNIQUE (vehicle_id)
    //    );
    //    """);
    //// Seed initial vehicle records (idempotent)
    //await db.Database.ExecuteSqlRawAsync("""
    //    INSERT INTO vehicles (id, vehicle_id, name, type, description) VALUES
    //        (1, 'TRK-001', 'Xe đầu kéo 1',     'truck',         'Xe đầu kéo container tuyến A'),
    //        (2, 'TRK-002', 'Xe đầu kéo 2',     'truck',         'Xe đầu kéo container tuyến B'),
    //        (3, 'YTR-001', 'Yard Tractor 1',    'yard-tractor',  'Kéo rơ-moóc trong cảng'),
    //        (4, 'YTR-002', 'Yard Tractor 2',    'yard-tractor',  'Kéo rơ-moóc trong cảng'),
    //        (5, 'FLK-001', 'Xe nâng 1',         'forklift',      'Xe nâng hàng khu vực kho A'),
    //        (6, 'FLK-002', 'Xe nâng 2',         'forklift',      'Xe nâng hàng khu vực kho B'),
    //        (7, 'CRN-001', 'Cẩu RTG 1',         'crane',         'Cẩu cổng bánh lốp số 1'),
    //        (8, 'CRN-002', 'Cẩu RTG 2',         'crane',         'Cẩu cổng bánh lốp số 2')
    //    ON CONFLICT (vehicle_id) DO NOTHING;
    //    """);
    //// Advance identity sequence past the seeded IDs to avoid PK conflicts on INSERT
    //await db.Database.ExecuteSqlRawAsync("""
    //    SELECT setval(
    //        pg_get_serial_sequence('vehicles', 'id'),
    //        (SELECT MAX(id) FROM vehicles)
    //    );
    //    """);
}

app.Run();
